spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yarden_test
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: "org.hibernate.dialect.MySQL8InnoDBDialect"
    show-sql: true
  graphql:
    servlet:
      mapping: /graphql
      enabled: true
      corsEnabled: true
    graphiql:
      enabled: true
server:
  port: ${MY_PORT}

